import type { Internship } from "./types";

// Fictional records used only to demonstrate the interface on first launch.
export const SEED_INTERNSHIPS: Internship[] = [
  {
    id: "sample-northstar",
    companyName: "Northstar Labs",
    companyLogoUrl: "",
    jobTitle: "Cloud Engineering Intern",
    roleTrack: "Cloud Engineering",
    description:
      "Support cloud infrastructure projects, document system changes, and help improve service reliability.",
    dateApplied: "2026-08-06",
    postingUrl: "https://example.com/jobs/cloud-engineering-intern",
    resumeVersion: "cloud-resume-v3.pdf",
    nextActionDate: "2026-08-13",
    recruiterName: "",
    recruiterEmail: "",
    recruiterPhone: "",
    notes:
      "Prepare one project example about deployment reliability and one question about intern mentorship.",
    status: "Applied",
    createdAt: "2026-08-06T15:00:00.000Z",
    updatedAt: "2026-08-06T15:00:00.000Z",
  },
  {
    id: "sample-atlas",
    companyName: "Atlas Cloud",
    companyLogoUrl: "",
    jobTitle: "Platform Engineering Intern",
    roleTrack: "DevOps",
    description:
      "Work with engineering teams on CI/CD workflows, developer tooling, and platform observability.",
    dateApplied: "2026-08-03",
    postingUrl: "https://example.com/jobs/platform-engineering-intern",
    resumeVersion: "devops-resume-v2.pdf",
    nextActionDate: "2026-08-10",
    recruiterName: "",
    recruiterEmail: "",
    recruiterPhone: "",
    notes:
      "Review the role requirements and practice explaining a CI/CD pipeline from commit through deployment.",
    status: "Phone Screen",
    createdAt: "2026-08-03T18:30:00.000Z",
    updatedAt: "2026-08-07T14:20:00.000Z",
  },
  {
    id: "sample-meridian",
    companyName: "Meridian Systems",
    companyLogoUrl: "",
    jobTitle: "Systems Software Intern",
    roleTrack: "Systems",
    description:
      "Build internal automation, troubleshoot Linux services, and contribute to performance testing.",
    dateApplied: "2026-07-30",
    postingUrl: "https://example.com/jobs/systems-software-intern",
    resumeVersion: "systems-resume-v1.pdf",
    nextActionDate: "2026-08-08",
    recruiterName: "",
    recruiterEmail: "",
    recruiterPhone: "",
    notes:
      "Refresh process, memory, networking, and debugging fundamentals before the technical conversation.",
    status: "Technical Interview",
    createdAt: "2026-07-30T17:00:00.000Z",
    updatedAt: "2026-08-05T19:15:00.000Z",
  },
  {
    id: "sample-pine",
    companyName: "Pine Digital",
    companyLogoUrl: "",
    jobTitle: "Software Engineering Intern",
    roleTrack: "Software Engineering",
    description:
      "Deliver a scoped product feature with testing, code review, and cross-functional collaboration.",
    dateApplied: "2026-07-22",
    postingUrl: "https://example.com/jobs/software-engineering-intern",
    resumeVersion: "software-resume-v4.pdf",
    nextActionDate: "2026-08-15",
    recruiterName: "",
    recruiterEmail: "",
    recruiterPhone: "",
    notes:
      "Prepare two behavioral stories covering ownership, debugging, and collaboration across a team.",
    status: "Waitlist",
    createdAt: "2026-07-22T15:40:00.000Z",
    updatedAt: "2026-08-02T20:00:00.000Z",
  },
  {
    id: "sample-forgeworks",
    companyName: "ForgeWorks",
    companyLogoUrl: "",
    jobTitle: "Security Engineering Intern",
    roleTrack: "Security",
    description:
      "Assist with secure configuration reviews, application testing, and remediation documentation.",
    dateApplied: "2026-07-18",
    postingUrl: "https://example.com/jobs/security-engineering-intern",
    resumeVersion: "security-resume-v2.pdf",
    nextActionDate: "",
    recruiterName: "",
    recruiterEmail: "",
    recruiterPhone: "",
    notes:
      "Record what was learned from the outcome and update the preparation checklist before the next application.",
    status: "Rejected",
    createdAt: "2026-07-18T21:00:00.000Z",
    updatedAt: "2026-07-29T21:00:00.000Z",
  },
];
